version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/
    links:
      - app
    depends_on:
      - app
    environment:
      - DB_HOST=db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    restart: unless-stopped
    links:
      - db
    networks:
      - default
      - laravel_network
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cell_phones
      # Regular user for application
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - default
      - laravel_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=1
    depends_on:
      - db
    links:
      - db
    networks:
      - default
      - laravel_network
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - default
      - laravel_network
volumes:
  db_data:
networks:
  laravel_network:
    driver: bridge