<<<<<<< HEAD
services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis

    mysql:
        image: "mysql:8.0"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - ./mysql/cell_phones.sql:/docker-entrypoint-initdb.d/cell_phones.sql 
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:mysql
        ports:
            - 8080:80
        environment:
            MYSQL_USERNAME: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            PMA_HOST: mysql
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
=======
version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/
    links:
      - app
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    restart: unless-stopped
    links:
      - db
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cell_phones
      MYSQL_USER: root
      MYSQL_PASSWORD: root
   
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
    links:
      - db
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
>>>>>>> 91c698627fd695c05faa1935846aa5e9f4ed8764
volumes:
  db_data:

  